theme = "base16_default"

[editor]
# line-number = "relative"
cursorline = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "block"

[editor.statusline]
#left = ["mode", "spinner"]
#center = ["file-name"]
#right = ["diagnostics", "position", "file-encoding", "file-type"]
#separator = "│"
#mode.normal = "NORMAL"
#mode.insert = "INSERT"
#mode.select = "SELECT"

[editor.file-picker]
# file picker is handy
hidden = false

[editor.soft-wrap]
enable = true

[editor.whitespace.render]
tab = "all"
newline = "none"

[editor.whitespace.characters]
nbsp = "⍽"
tab = "→"
tabpad = "·" # Tabs will look like "→···" (depending on tab width)

[editor.indent-guides]
render = false
character = "┆" # Some characters that work well: "▏", "┆", "┊", "⸽"
skip-levels = 1

[editor.lsp]
display-messages = true

[keys.normal]
g = { a = "code_action" } # Maps `ga` to show possible code actions
"ret" = ["move_line_down", "goto_first_nonwhitespace"] # Maps the enter key to move to start of next line
X = "extend_line_above"
D = "delete_char_backward"

[keys.insert]
j = { k = "normal_mode" } # Maps `jk` to exit insert mode