colorscheme desertex

# highlighers
add-highlighter global/ number-lines -relative
add-highlighter global/ wrap
add-highlighter global/ show-matching

## indentation
set-option global tabstop     4
set-option global indentwidth 4

# tabs to spaces
hook global InsertChar \t %{
    exec -draft h@
}

# keybindings
map global normal '#' ': comment-line<ret>'                   -docstring 'comment-line'
map global user <space> :                                     -docstring 'command (: alias)'

## Hooks

# exit insert mode with jk
hook global InsertChar j %{ try %{
      execute-keys -draft hH <a-k>jj<ret> d
      execute-keys <esc>
}}

hook global InsertChar k %{ try %{
      execute-keys -draft hH <a-k>jk<ret> d
      execute-keys <esc>
      write
}}

# use tab and s-tab for autocomplete selection
hook global InsertCompletionShow .* %{
      map window insert <tab> <c-n>
      map window insert <s-tab> <c-p>
}
hook global InsertCompletionHide .* %{
      unmap window insert <tab> <c-n>
      unmap window insert <s-tab> <c-p>
}

# LSP Stuff
eval %sh{kak-lsp --kakoune -s $kak_session}
lsp-enable

# kak-plug

evaluate-commands %sh{
    plugins="$kak_config/plugins"
    mkdir -p "$plugins"
    [ ! -e "$plugins/plug.kak" ] && \
        git clone -q https://github.com/andreyorst/plug.kak.git "$plugins/plug.kak"
    printf "%s\n" "source '$plugins/plug.kak/rc/plug.kak'"
}
plug "andreyorst/plug.kak" noload

plug "pepe/janet.kak"
plug 'delapouite/kakoune-buffers' %{
    map global normal ^ q
    map global normal <a-^> Q
    map global normal q b
    map global normal Q B
    map global normal <a-q> <a-b>
    map global normal <a-Q> <a-B>
    map global normal b ': enter-buffers-mode<ret>' -docstring 'buffers'
    map global normal B ': enter-user-mode -lock buffers<ret>' -docstring 'buffers (lock)'
}
#face global InfoDefault               Information
#face global InfoBlock                 Information
#face global InfoBlockQuote            Information
#face global InfoBullet                Information
#face global InfoHeader                Information
#face global InfoLink                  Information
#face global InfoLinkMono              Information
#face global InfoMono                  Information
#face global InfoRule                  Information
#face global InfoDiagnosticError       Information
#face global InfoDiagnosticHint        Information
#face global InfoDiagnosticInformation Information
#face global InfoDiagnosticWarning     Information
