layouts:
    - tall
    - fullscreen
    # - tall-right
    #- wide
    - two-pane
    #- 3column-left
    #- middle-wide
    #- 3column-right
    #- 4column-left
    #- 4column-right
    #- column
    #- row
    - floating
    #- widescreen-tall
    #- widescreen-tall-right
    #- bsp

# Add "command" to the default mods
mod1:
    - option
    - shift
mod2:
    - option
    - shift
    - control

# Modify the amethyst relaunch to use x and not z
relaunch-amethyst:
    mod: mod2
    key: x

focus-main:
    mod: mod1
    key: backspace

swap-main:
    mod: mod2
    key: enter

# Enable focus-follows-mouse
mouse-follows-focus: true
focus-follows-mouse: false

# Add margin between windows
window-margins: true
window-margin-size: 7

# Padding
screen-padding-left:  0
screen-padding-right: 0

smart-window-margins:   true
mouse-swaps-windows:    true
mouse-resizes-windows:  true

# Floating Window List
floating:
    - com.kapeli.dashdoc
    - com.apple.systempreferences
    - com.cisco.anyconnect.gui
