#! /bin/bash
# TODO: This shit doesn't even work
# Create a file from a path and create directories as needed.
mktouch() {
    echo "WARNING: THIS SHIT DOESNT EVEN WORK";
    exit 1
    if [ $# -lt 1 ]; then
        echo "Missing argument";
        return 1;
    fi

    for f in "$@"; do
        mkdir -p -- "$(dirname -- "$f")"
        touch -- "$f"
    done
}

mktouch
